resize replacement
mjauvin/wn-ngmedia-plugin pull request #5
Opened 2021-05-01 15:00 UTC by helmutkaufmann

introduced repalcemement for resize, will return the "best" image format unless format is set explicitly.

2021-05-01 15:32 UTC, mjauvin requested changes

2021-05-01 15:32 UTC, mjauvin commented on Plugin.php
> +                'resize' =>  [TwigExtensions::class, 'ngresize'],
why override this? why not use ngresize?

2021-05-01 15:32 UTC, mjauvin commented on classes/TwigExtensions.php
> +
wouldn't you need to check browser support as well?

2021-05-01 15:32 UTC, mjauvin commented on classes/TwigExtensions.php
> +		// If the extension is set explicitly, honor it.
same here, what if browser does not support this format?

2021-05-01 16:01 UTC, helmutkaufmann commented on Plugin.php
> +                'resize' =>  [TwigExtensions::class, 'ngresize'],
This would allow a replacement of the existing Twig functionality without having to change any .htm code. Alternatively, we could make it an option in the backend for the admin to chose from.

2021-05-01 16:46 UTC, mjauvin commented on classes/TwigExtensions.php
> +
not sure what you mean by "this is how it works today"

2021-05-02 04:38 UTC, helmutkaufmann commented on classes/TwigExtensions.php
> +
This was from the original code fragment, which I did not change. I have tried to reason why it is in and could not come up with a good conclusion - this if clause should go.
My previous comment was misleading, I had the next if statement in mind.

2021-05-02 04:38 UTC, helmutkaufmann commented on classes/TwigExtensions.php
> +		// If the extension is set explicitly, honor it.
See above, this should go.

2021-05-02 05:26 UTC, closed without merging

2021-05-02 05:27 UTC, helmutkaufmann commented
Further changes made. All changes merged in single PR.