Consolidated PR
mjauvin/wn-ngmedia-plugin pull request #8
Opened 2021-05-02 05:23 UTC by helmutkaufmann

Hi Marc. Trying to work my way around GitHub. I have consolidated all into a single PR. Removed the public_path if statements as I cannot figure out why they were there in the first place. Also changed filter name from resize to ngresize.

2021-05-02 05:57 UTC, helmutkaufmann reviewed
Tnx. The filter works just fine on my website for all galleries. Tested with multiple browsers and devices.

2021-05-02 13:39 UTC, mjauvin commented on classes/TwigExtensions.php
> +	$path = public_path(parse_url($image, PHP_URL_PATH));
What's the point of continuing if the file is missing?

This is the expected behavior to return the filename as provided in this case.

2021-05-02 13:40 UTC, mjauvin commented on classes/TwigExtensions.php
> +	    	$path = public_path(parse_url($image, PHP_URL_PATH));
You need to check for the file exitence here as well.

2021-05-02 13:45 UTC, mjauvin commented on classes/TwigExtensions.php
> +	$path = public_path(parse_url($image, PHP_URL_PATH));
This is also what the core `resize` filter does, so we want to keep this behavior. If yo uthink this is not right, open a an issue to core repo so we can discuss this.

2021-05-03 06:20 UTC, helmutkaufmann commented on classes/TwigExtensions.php
> +	$path = public_path(parse_url($image, PHP_URL_PATH));
Ok. Added it back in.

2021-05-03 06:20 UTC, helmutkaufmann commented on classes/TwigExtensions.php
> +	    	$path = public_path(parse_url($image, PHP_URL_PATH));
OK, added back in

2021-05-03 12:35 UTC, mjauvin requested changes

2021-05-03 12:35 UTC, mjauvin commented on classes/TwigExtensions.php
> +	if (!File::exists($path)) {
Indentation must be 4 characters like everywhere else.

2021-05-03 12:35 UTC, mjauvin commented on classes/TwigExtensions.php
> +		}
We need to check if browser supports this file type.

2021-05-03 12:35 UTC, mjauvin commented on classes/TwigExtensions.php
> +		}
We need to check if browser supports this file type.

2021-05-03 17:56 UTC, mjauvin commented on classes/TwigExtensions.php
> +	if (!File::exists($path)) {
hmm, looks like it is, eventhough it looked like 2 in the diff... never mind.

2021-05-04 03:33 UTC, helmutkaufmann commented on classes/TwigExtensions.php
> +		}
Why would we want to do that? The user would like an explicit extension, so let us produce it. That makes sense as the user might also want to use the resulting image for download purposes only. Also, what would we produce in case the browser cannot display it? Returning the same image is not a solution as this might also not be accepted by the browser . So I think , this fragment actually achieves what it should.

2021-05-04 04:00 UTC, helmutkaufmann commented on classes/TwigExtensions.php
> +		}
Actually, I am giving up on this... as it will not render the chosen image format as per your previous conversation.

2021-05-04 10:44 UTC, merged